---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - terraform.terrajob.htonkovac.com
  resources:
  - terrajobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.terrajob.htonkovac.com
  resources:
  - terrajobs/finalizers
  verbs:
  - update
- apiGroups:
  - terraform.terrajob.htonkovac.com
  resources:
  - terrajobs/status
  verbs:
  - get
  - patch
  - update
