# permissions for end users to edit terrajobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: terrajob-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: terrajob
    app.kubernetes.io/part-of: terrajob
    app.kubernetes.io/managed-by: kustomize
  name: terrajob-editor-role
rules:
- apiGroups:
  - terraform.terrajob.htonkovac.com
  resources:
  - terrajobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.terrajob.htonkovac.com
  resources:
  - terrajobs/status
  verbs:
  - get
